### PR TITLE
Fix bugs

### PR DESCRIPTION
**Pull request by dandean**
This patch fixes several longstanding issues.

### CODE REVIEW

**Comment by takeo** [comment]
Does @ieure know you're borrowing his joke?

**Comment by ieure** [comment]
"borrowing"

**Comment by OscarGodson** [comment]
I don't accept PRs without tests

**Comment by dandean** [comment]
What do you mean? Oooh
When you nod your head yes

But you wanna say no
What do you mean? Heeey
When you don’t want me to move
But you tell me to go
What do you mean?
What do you mean?
Said we’re running out of time
What do you mean?
Oh oh oh What do you mean?
Better make up your mind
What do you mean?

You’re so indecisive of what I’m saying
Trying to catch the beat, make up your heart.
Don't know if you're happy, or complaining.

Don’t want for us to end where do I start
First you wanna go to the left and you want to turn right
Wanna argue all day, making love all night.

First you up and you’re down and then between

Ohh I really want to know…
What do you mean?

When you nod your head yes
But you wanna say no
What do you mean?
When you don't want me to move
But you tell me to go
What do you mean?
What do you mean?
Said we’re running out of time
What do you mean?
Better make up your mind
What do you mean?
You’re overprotective when I’m leaving
Trying to compromise but I can’t win
You wanna make a point but you keep preaching
You had me from the start won’t let this end
First you wanna go to the left then you want to turn right
Wanna argue all day make love all night
First you up and you’re down then you're between
Ohh I really want to know…
What do you mean? Ooh..
When you nod your head yes
But you wanna say no.
What do you mean? (oh what do you mean)
When you don’t want me to move
But you tell me to go
What do you mean?
I wanna know
Oh what do you mean?
(Ooh)
Said you’re running out of time
What do you mean? (ah baby)
Oh oh oh what do you mean?

Better make up your mind
What do you mean?
When you nod your head yes, but you wanna say no
What do you mean?
(You're so confusing baby)
Heyyy, when you don't want me to move, 
But you tell me to go
What do you mean?
What do you mean?
Said we're running out of time
What do you mean?
Oh oh oh what do you mean?
Better make up your mind 
What do you mean?

**Comment by dandean** [comment]
Test me? Can't test me
None of them man can't test me, can't test me
None of them man can't test me
I said a double negative, can't test me
None of them man can't test me, can't test me
None of them man can test me
I said a triple negative, can't test me
I said none of them man can test me

I've got new tees with no vowels like Drake
Man are gassed when they see me, I'm like "mate"
I understand my face is bait
Drive too close behind me, I might brake
Man wanna take pictures of my face
Man wanna take pictures of my plate
Man wanna take pictures so bad
I press the brake and get a whiplash claim
Man must think that I'm a celeb
Cause the whip cost an arm and a leg
But no, I make grime on the regs
And I saved for a year to buy one of them
You've seen my black face on your TV screen
So you keep thinking this shit's easy
Try copy me fam, you'll see
That nobody wants your shit CD

Do I wanna spit a bar? Yes please
I said do I wanna spit a bar? Yes please
And I still spit on the best beats
You don't like it? Suck on these testes
Boy dem still ain't arrest me
But they're onto me like the king chess piece
None of their lies impress me
And none of them guys can test me

They can't test me, test me
None of them man can test me
None of them man can test me
None of them man can test me

I've got a roadman jacket from Nasir Mazhar
Designed with Joseph Adenuga
I zip my hood up when I'm driving my car
If I see a [?] like rah
Yo Jme, big fan, quick pic?
I be like nah fam, don't chat shit
You better show me your phone
Best have one of my tunes there, or at least a ringtone
Don't try take man for Eiffel Tower
Don't try take man for no Big Ben
Man wanna bred me to show their friends
Don't try take me for a JPEG
Unless you got me on the MP3
Just say wah gwan when you see me
I'm on point still, keeping it real
You feel what I'm saying cause I say what I feel

Hold tight the people who leave grime and think you're gonna achieve something. It don't work, I tried it way before all of you. Bye

Blud, I'll leave you gutless
Come to your ends, send for the cutlass
One time, I'm going on reckless
Come to the ends, jack your bredrins twice
Blud, I'll leave you gutless
Come to your ends, send for the cutlass
One time, I'm going on reckless
Come to the ends, jack your necklace
And your chaps and earrings too
Serious, I'm preparing to
(Beat you up), I'll be there in two
Serious, I'm raring to
(Beat you up), stop staring too
Serious, I'm not gearing to
(Beat you up), you're daring
But you're not bad, I don't care what you're wearing
You're not serious
Cause you got your name on your Nike Air Dunks, blud
(I'll beat you up)
You're not serious cause you shot two kis of punk, blud
(I'll beat you up)
You're not serious, I don't care if you've got a yout, blud
(I'll beat you up)
You're not serious cause you got an Akademiks tracksuit, blud
(I'll beat you up)
You're not serious cause you got low-profile tyres, blud
(I'll beat you up)
You're not serious cause your name's on couple flyers, blud
(I'll beat you up)
You're not serious, I don't care if you've got your own charm, blud
(I'll beat you up)
You're not serious, can't clash Jme, are you dumb, blud?
(I'll beat you up)

Yeah, Joker
Boy Better Know what
If you don't know by now then you won't know
Cause you should already know
If you don't know by now then you won't know
Cause you should already know

**Comment by OscarGodson** [comment]
Is there a way to have this song autoplay when people submit PRs without tests because this would be very effective

**Pull request closed without merging**
